name: CheckVersionsTools
run-name: ${{ inputs.identifier }}

on:
  workflow_dispatch:

jobs:
  check-required-env-variables:
    name: "required-env-variables"
    runs-on: self-hosted
    environment: dev-azure
    steps:
      - name: Run kubectl version
        run: |
          kubectl version || echo "kubectl version failed"

      - name: Run solc version
        run: |
          solc --version || echo "solc version failed"

      - name: Run besu version
        run: |
          besu --version || echo "besu version failed"

      - name: Run java version
        run: |
          java -version || echo "java version failed"
