name: Hyperledger Besu Deploy Backend API Azure - Tear Down
run-name: ${{ inputs.identifier }}

on:
  workflow_dispatch:
    inputs:
      identifier:
        description: 'Variable that represents the release identifier'
        required: true
        type: string  
      parameters:
        description: 'Variables in json wrapped'
        required: true

jobs:
  check-required-env-variables:
    name: "required-env-variables"
    runs-on: runner-azure
    environment: dev-azure
    steps:
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(vars) }}
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}       
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ github.event.inputs.parameters }}
      - name: Print envs - test
        run: |
          echo "Printing all environment variables:"
          env
      - name: Checking APP_ID
        if: ${{ env.APP_ID == '' }} 
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('APP_ID is required')
      - name: Checking API_VARIABLES
        if: ${{ env.API_VARIABLES == '' }} 
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('API_VARIABLES is required')
      - name: Checking DEPLOY_ID
        if: ${{ env.DEPLOY_ID == '' }} 
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('DEPLOY_ID is required')
      - name: Checking COMPONENT_ID
        if: ${{ env.COMPONENT_ID == '' }} 
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('COMPONENT_ID is required') 
      - name: Checking COMPONENT_NAME
        if: ${{ env.COMPONENT_NAME == '' }} 
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('COMPONENT_NAME is required')     
      - name: Checking CUSTOMER_ID
        if: ${{ env.CUSTOMER_ID == '' }} 
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('CUSTOMER_ID is required') 
      - name: Checking NETWORK_ID
        if: ${{ env.NETWORK_ID == '' }} 
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('NETWORK_ID is required')
      - name: Checking NODE_ID
        if: ${{ env.NODE_ID == '' }} 
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('NODE_ID is required')        
                
  teardown-backend-api:
    name: "teardown-backend-api"
    runs-on: runner-azure
    needs: [check-required-env-variables]
    environment: dev-azure
    steps:
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(vars) }}
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}       
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ github.event.inputs.parameters }}    
      - name: Checkout Azure Besu DevOps repo
        run: |
          rm -rf ${{ vars.BESU_REPO_PATH }}
          git clone https://$(echo $AZURE_GIT_ACCESS_TOKEN)@${{ vars.BESU_REPO_URL }}
          cd ${{ vars.BESU_REPO_PATH }}
          git checkout ${{ vars.BRANCH }}
          echo "Cloned Azure DevOps repository"   
      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}'
          files: '["**/infra-requirements.yaml"]'
      - name: Installing collection
        run: |
          cd ${{ vars.BESU_REPO_PATH }}
          ansible-galaxy collection install -r infra-requirements.yaml -vvvv
      - name: Drop API
        run: |
          cd ${{ vars.BESU_REPO_PATH }}
          ansible-playbook -i inventories/hosts.yaml ${{ vars.BESU_NODE_PLAYBOOK }} --tags="login,tear_down" -vvvv