name: Hyperledger Besu Network Azure
run-name: ${{ inputs.identifier }}

on:
  workflow_dispatch:
    inputs:   
      identifier:
        description: 'Variable that represents the release identifier'
        required: true
        type: string  
      parameters:
        description: 'Variables in json wrapped'
        required: true

env:
  BESU_CONSENSUS_ALG: ${{ fromJson(github.event.inputs.parameters).BESU_CONSENSUS_ALG || 'QBFT' }}
  BOOTNODES: ${{ fromJson(github.event.inputs.parameters).BOOTNODES || '' }}
  COMPONENT_ID: ${{ fromJson(github.event.inputs.parameters).COMPONENT_ID || '' }}
  COMPONENT_NAME: ${{ fromJson(github.event.inputs.parameters).COMPONENT_NAME || '' }}
  COUNTRY: ${{ fromJson(github.event.inputs.parameters).COUNTRY || '' }}
  CUSTOMER_ID: ${{ fromJson(github.event.inputs.parameters).CUSTOMER_ID || '' }}
  DNS_TYPE: ${{ fromJson(github.event.inputs.parameters).DNS_TYPE || 'public' }}
  DNS_ZONE: ${{ fromJson(github.event.inputs.parameters).DNS_ZONE || 'blockchainlab.network' }} 
  LOCATION: ${{ fromJson(github.event.inputs.parameters).LOCATION || '' }}
  MIN_GAS_PRICE: ${{ fromJson(github.event.inputs.parameters).MIN_GAS_PRICE || '0' }} 
  NET_NAME: ${{ fromJson(github.event.inputs.parameters).NET_NAME || 'ks-net' }} 
  NETWORK_ID: ${{ fromJson(github.event.inputs.parameters).NETWORK_ID || '' }}
  NODE_COUNT: ${{ fromJson(github.event.inputs.parameters).NODE_COUNT || '4' }} 
  ORGANIZATION: ${{ fromJson(github.event.inputs.parameters).ORGANIZATION || '' }}
  QUORUM_EXPLORER_IMAGE_TAG: ${{ fromJson(github.event.inputs.parameters).QUORUM_EXPLORER_IMAGE_TAG || '8091' }} 
  SUBNET_NAME: ${{ fromJson(github.event.inputs.parameters).SUBNET_NAME || 'ks-subnet' }} 
  VALIDATORS: ${{ fromJson(github.event.inputs.parameters).VALIDATORS || '' }}
  ENV: ${{ fromJson(github.event.inputs.parameters).ENV || '' }}

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
    - name: Create a file with environment variables
      run: |
        echo "COMPONENT_NAME=${{ env.COMPONENT_NAME }}" >> vars.txt
        echo "BESU_CONSENSUS_ALG=${{ env.BESU_CONSENSUS_ALG }}" >> vars.txt
        echo "BOOTNODES=${{ env.BOOTNODES }}" >> vars.txt
    - name: Upload vars file
      uses: actions/upload-artifact@v3
      with:
        name: vars
        path: vars.txt

  read-file:
    runs-on: ubuntu-latest
    needs: create-file
    steps:
    - name: Download vars file
      uses: actions/download-artifact@v3
      with:
        name: vars
    - name: Read the file
      run: cat vars.txt

  read-bootnodes:
    runs-on: ubuntu-latest
    needs: create-file
    steps:
    - name: Download vars file
      uses: actions/download-artifact@v3
      with:
        name: vars
    - name: Read BOOTNODES value
      run: |
        BOOTNODES=$(grep "BOOTNODES" vars.txt | cut -d'=' -f2)
        echo "BOOTNODES is: $BOOTNODES"
