name: Hyperledger Besu Network
run-name: ${{ inputs.identifier }}

on:
  workflow_dispatch:
    inputs:   
      identifier:
        description: 'Variable that represents the release identifier'
        required: true
        type: string  
      parameters:
        description: 'Variables in json wrapped'
        required: true
env:
  ARTIFACT_REGISTRY: ${{ vars.ARTIFACT_REGISTRY }}
  AZURE_GIT_ACCESS_TOKEN: ${{ secrets.AZURE_GIT_ACCESS_TOKEN }}
  BESU_CONSENSUS_ALG: ${{ fromJson(github.event.inputs.parameters).BESU_CONSENSUS_ALG }} || "QBFT"
  BOOTNODES: ${{ fromJson(github.event.inputs.parameters).BOOTNODES || 'default-bootnode-value' }}
  COMPONENT_ID: ${{ fromJson(github.event.inputs.parameters).COMPONENT_ID }}
  COMPONENT_NAME: ${{ fromJson(github.event.inputs.parameters).COMPONENT_NAME }}
  COUNTRY: ${{ fromJson(github.event.inputs.parameters).COUNTRY }}
  CUSTOMER_ID: ${{ fromJson(github.event.inputs.parameters).CUSTOMER_ID }}
  DNS_TYPE: ${{ fromJson(github.event.inputs.parameters).DNS_TYPE }} || "public"
  DNS_ZONE: ${{ fromJson(github.event.inputs.parameters).DNS_ZONE }} || 'blockchainlab.network'
  LOCATION: ${{ fromJson(github.event.inputs.parameters).LOCATION }}
  MIN_GAS_PRICE: ${{ fromJson(github.event.inputs.parameters).MIN_GAS_PRICE }} || "0"
  NET_NAME: ${{ fromJson(github.event.inputs.parameters).NET_NAME }} || "ks-net"
  NETWORK_ID: ${{ fromJson(github.event.inputs.parameters).NETWORK_ID }}
  NODE_COUNT: ${{ fromJson(github.event.inputs.parameters).NODE_COUNT }} || "4"
  ORGANIZATION: ${{ fromJson(github.event.inputs.parameters).ORGANIZATION }}
  QUORUM_EXPLORER_IMAGE_TAG: ${{ fromJson(github.event.inputs.parameters).QUORUM_EXPLORER_IMAGE_TAG }} || "8091"
  SUBNET_NAME: ${{ fromJson(github.event.inputs.parameters).SUBNET_NAME }} || "ks-subnet"
  VALIDATORS: ${{ fromJson(github.event.inputs.parameters).VALIDATORS }}
  ENV: ${{ fromJson(github.event.inputs.parameters).ENV }}

jobs:
  check-required-env-variables:
    name: "required-env-variables"
    runs-on: self-hosted
    environment: dev
    steps:
      - name: Checking BOOTNODES
        if: ${{ BOOTNODES }} == ''
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('BOOTNODES is required')
  display-variables:
    name: "Teste"
    runs-on: self-hosted
    environment: dev
    steps:
    - name: Use variables
      run: |
        echo "branch variable : $BRANCH"
        echo "ARTIFACT_REGISTRY variable : $ARTIFACT_REGISTRY"
        echo "CLIENT_ID variable : $CLIENT_ID"
        echo "secret : $AZURE_GIT_ACCESS_TOKEN"
      env:
        AZURE_GIT_ACCESS_TOKEN: ${{ secrets.AZURE_GIT_ACCESS_TOKEN }}
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: self-hosted
    environment: dev
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_GIT_ACCESS_TOKEN }}
          tenant-id: ${{ secrets.AZURE_GIT_ACCESS_TOKEN }}
          subscription-id: ${{ secrets.AZURE_GIT_ACCESS_TOKEN }}

