name: Hyperledger Besu Network Azure
run-name: ${{ inputs.identifier }}

on:
  workflow_dispatch:
    inputs:   
      identifier:
        description: 'Variable that represents the release identifier'
        required: true
        type: string  
      parameters:
        description: 'Variables in json wrapped'
        required: true

jobs:
  set-environment-variables:
    name: "Set Global Environment Variables"
    runs-on: [ self-hosted, azure ]
    steps:
      - name: Export environment variables globally
        run: |
          echo "BESU_CONSENSUS_ALG=${{ fromJson(github.event.inputs.parameters).BESU_CONSENSUS_ALG || 'QBFT' }}" >> $GITHUB_ENV
          echo "BOOTNODES=${{ fromJson(github.event.inputs.parameters).BOOTNODES || '' }}" >> $GITHUB_ENV
          echo "COMPONENT_ID=${{ fromJson(github.event.inputs.parameters).COMPONENT_ID || '' }}" >> $GITHUB_ENV
          echo "COMPONENT_NAME=${{ fromJson(github.event.inputs.parameters).COMPONENT_NAME || '' }}" >> $GITHUB_ENV
          echo "COUNTRY=${{ fromJson(github.event.inputs.parameters).COUNTRY || '' }}" >> $GITHUB_ENV
          echo "CUSTOMER_ID=${{ fromJson(github.event.inputs.parameters).CUSTOMER_ID || '' }}" >> $GITHUB_ENV
          echo "DNS_TYPE=${{ fromJson(github.event.inputs.parameters).DNS_TYPE || 'public' }}" >> $GITHUB_ENV
          echo "DNS_ZONE=${{ fromJson(github.event.inputs.parameters).DNS_ZONE || 'blockchainlab.network' }}" >> $GITHUB_ENV
          echo "LOCATION=${{ fromJson(github.event.inputs.parameters).LOCATION || '' }}" >> $GITHUB_ENV
          echo "MIN_GAS_PRICE=${{ fromJson(github.event.inputs.parameters).MIN_GAS_PRICE || '0' }}" >> $GITHUB_ENV
          echo "NET_NAME=${{ fromJson(github.event.inputs.parameters).NET_NAME || 'ks-net' }}" >> $GITHUB_ENV
          echo "NETWORK_ID=${{ fromJson(github.event.inputs.parameters).NETWORK_ID || '' }}" >> $GITHUB_ENV
          echo "NODE_COUNT=${{ fromJson(github.event.inputs.parameters).NODE_COUNT || '4' }}" >> $GITHUB_ENV
          echo "ORGANIZATION=${{ fromJson(github.event.inputs.parameters).ORGANIZATION || '' }}" >> $GITHUB_ENV
          echo "QUORUM_EXPLORER_IMAGE_TAG=${{ fromJson(github.event.inputs.parameters).QUORUM_EXPLORER_IMAGE_TAG || '8091' }}" >> $GITHUB_ENV
          echo "SUBNET_NAME=${{ fromJson(github.event.inputs.parameters).SUBNET_NAME || 'ks-subnet' }}" >> $GITHUB_ENV
          echo "VALIDATORS=${{ fromJson(github.event.inputs.parameters).VALIDATORS || '' }}" >> $GITHUB_ENV
          echo "ENV=${{ fromJson(github.event.inputs.parameters).ENV || '' }}" >> $GITHUB_ENV

  check-required-env-variables:
    name: "required-env-variables"
    runs-on: [ self-hosted, azure ]
    needs: [set-environment-variables]  # Garantir que as variáveis sejam definidas antes deste job
    environment: dev
    steps:
      - name: Validate envs - temp
        run: |
          echo "BESU_CONSENSUS_ALG: $BESU_CONSENSUS_ALG"
          echo "BOOTNODES: $BOOTNODES"
          echo "COMPONENT_ID: $COMPONENT_ID"
          echo "COMPONENT_NAME: $COMPONENT_NAME"
          echo "COUNTRY: $COUNTRY"
          echo "CUSTOMER_ID: $CUSTOMER_ID"
          echo "DNS_TYPE: $DNS_TYPE"
          echo "DNS_ZONE: $DNS_ZONE"
          echo "LOCATION: $LOCATION"
          echo "MIN_GAS_PRICE: $MIN_GAS_PRICE"
          echo "NET_NAME: $NET_NAME"
          echo "NETWORK_ID: $NETWORK_ID"
          echo "NODE_COUNT: $NODE_COUNT"
          echo "ORGANIZATION: $ORGANIZATION"
          echo "QUORUM_EXPLORER_IMAGE_TAG: $QUORUM_EXPLORER_IMAGE_TAG"
          echo "SUBNET_NAME: $SUBNET_NAME"
          echo "VALIDATORS: $VALIDATORS"
          echo "ENV: $ENV"

      - name: Checking BOOTNODES
        if: ${{ env.BOOTNODES == '' }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('BOOTNODES is required')
      - name: Checking COMPONENT_ID
        if: ${{ env.COMPONENT_ID == '' }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('COMPONENT_ID is required')
      - name: Checking COMPONENT_NAME
        if: ${{ env.COMPONENT_NAME == '' }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('COMPONENT_NAME is required')
      - name: Checking CUSTOMER_ID
        if: ${{ env.CUSTOMER_ID == '' }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('CUSTOMER_ID is required')
      - name: Checking NETWORK_ID
        if: ${{ env.NETWORK_ID == '' }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('NETWORK_ID is required')
      - name: Checking VALIDATORS
        if: ${{ env.VALIDATORS == '' }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('VALIDATORS is required')

  checkout-anisble-pipelines:
    name: "checkout-ansible-pipelines"
    runs-on: [ self-hosted, azure ]
    needs: [check-required-env-variables]
    environment: dev-azure
    steps:
      - name: Checkout Azure DevOps repo
        env:
          AZURE_GIT_ACCESS_TOKEN: ${{ secrets.AZURE_GIT_ACCESS_TOKEN }}
        run: |
          rm -rf ${{ vars.FOUNDATION_REPO_PATH }}
          git clone https://$(echo $AZURE_GIT_ACCESS_TOKEN)@${{ vars.FOUNDATION_REPO_URL }}
          cd ${{ vars.FOUNDATION_REPO_PATH }}
          git checkout ${{ vars.BRANCH }}
          echo "Cloned Azure DevOps repository"

  create-namespace:
    name: "create-namespace"
    runs-on: [ self-hosted, azure ]
    needs: [checkout-anisble-pipelines]
    environment: dev-azure
    steps:
      - name: Running playbook to create namespace
        env:
          TIER: ${{ vars.TIER }}
          SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
          CLIENT_ID: ${{ vars.CLIENT_ID }}
          TENANT_ID: ${{ vars.TENANT_ID }}
          SECRET: ${{ secrets.SECRET }}
        run: |
          cd ${{ vars.FOUNDATION_REPO_PATH }}
          ansible-playbook -i inventories/hosts.yaml ${{ vars.NAMESPACE_PLAYBOOK }} -vvvv
