name: Hyperledger Besu Network
run-name: ${{ inputs.identifier }}

on:
  workflow_dispatch:
    inputs:   
      identifier:
        description: 'Variable that represents the release identifier'
        required: true
        type: string  
      parameters:
        description: 'Variables in json wrapped'
        required: true
env:
  BESU_CONSENSUS_ALG: ${{ fromJson(github.event.inputs.parameters).BESU_CONSENSUS_ALG || 'QBFT' }}
  BOOTNODES: ${{ fromJson(github.event.inputs.parameters).BOOTNODES || '' }}
  COMPONENT_ID: ${{ fromJson(github.event.inputs.parameters).COMPONENT_ID || '' }}
  COMPONENT_NAME: ${{ fromJson(github.event.inputs.parameters).COMPONENT_NAME || '' }}
  COUNTRY: ${{ fromJson(github.event.inputs.parameters).COUNTRY || '' }}
  CUSTOMER_ID: ${{ fromJson(github.event.inputs.parameters).CUSTOMER_ID || '' }}
  DNS_TYPE: ${{ fromJson(github.event.inputs.parameters).DNS_TYPE || 'public' }}
  DNS_ZONE: ${{ fromJson(github.event.inputs.parameters).DNS_ZONE || 'blockchainlab.network' }} 
  LOCATION: ${{ fromJson(github.event.inputs.parameters).LOCATION || '' }}
  MIN_GAS_PRICE: ${{ fromJson(github.event.inputs.parameters).MIN_GAS_PRICE || '0' }} 
  NET_NAME: ${{ fromJson(github.event.inputs.parameters).NET_NAME || 'ks-net' }} 
  NETWORK_ID: ${{ fromJson(github.event.inputs.parameters).NETWORK_ID || '' }}
  NODE_COUNT: ${{ fromJson(github.event.inputs.parameters).NODE_COUNT || '4' }} 
  ORGANIZATION: ${{ fromJson(github.event.inputs.parameters).ORGANIZATION || '' }}
  QUORUM_EXPLORER_IMAGE_TAG: ${{ fromJson(github.event.inputs.parameters).QUORUM_EXPLORER_IMAGE_TAG || '8091' }} 
  SUBNET_NAME: ${{ fromJson(github.event.inputs.parameters).SUBNET_NAME || 'ks-subnet' }} 
  VALIDATORS: ${{ fromJson(github.event.inputs.parameters).VALIDATORS || '' }}
  ENV: ${{ fromJson(github.event.inputs.parameters).ENV || '' }}

jobs:
  check-required-env-variables:
    name: "required-env-variables"
    runs-on: self-hosted
    environment: dev
    steps:
      - name: Checking BOOTNODES
        if: ${{ env.BOOTNODES == '' }} 
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('BOOTNODES is required')
      - name: Checking COMPONENT_ID
        if: ${{ env.COMPONENT_ID == '' }} 
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('COMPONENT_ID is required') 
      - name: Checking COMPONENT_NAME
        if: ${{ env.COMPONENT_NAME == '' }} 
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('COMPONENT_NAME is required')     
      - name: Checking CUSTOMER_ID
        if: ${{ env.CUSTOMER_ID == '' }} 
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('CUSTOMER_ID is required') 
      - name: Checking NETWORK_ID
        if: ${{ env.NETWORK_ID == '' }} 
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('NETWORK_ID is required')                 
  checkout-anisble-pipelines:
    name: "checkout-ansible-pipelines"
    runs-on: self-hosted
    needs: [check-required-env-variables]
    environment: dev
    steps:
      - name: Checkout Azure DevOps repo
        env:
          AZURE_GIT_ACCESS_TOKEN: ${{ secrets.AZURE_GIT_ACCESS_TOKEN }}
        run: |
          rm -rf ${{ vars.FOUNDATION_REPO_PATH }}
          git clone https://$(echo $AZURE_GIT_ACCESS_TOKEN)@${{ vars.FOUNDATION_REPO_URL }}
          cd ${{ vars.FOUNDATION_REPO_PATH }}
          echo "Running copy of sa-key.json"
          echo "${{ secrets.SAKEY }}" >> sa-key.json
          cat sa-key.json
          git checkout ${{ vars.BRANCH }}
          echo "Cloned Azure DevOps repository"
  create-namespace:
    name: "create-namespace"
    runs-on: self-hosted
    needs: [checkout-anisble-pipelines]
    environment: dev
    steps:
      - name: Running playbook to create namespace
        run: |
          if [ -z "${{ env.BESU_CONSENSUS_ALG }}" ] || 
             [ -z "${{ env.BOOTNODES }}" ] || 
             [ -z "${{ env.COMPONENT_ID }}" ] || 
             [ -z "${{ env.COMPONENT_NAME }}" ] || 
             [ -z "${{ env.COUNTRY }}" ] || 
             [ -z "${{ env.CUSTOMER_ID }}" ] || 
             [ -z "${{ env.DNS_TYPE }}" ] || 
             [ -z "${{ env.DNS_ZONE }}" ] || 
             [ -z "${{ env.LOCATION }}" ] || 
             [ -z "${{ env.MIN_GAS_PRICE }}" ] || 
             [ -z "${{ env.NET_NAME }}" ] || 
             [ -z "${{ env.NETWORK_ID }}" ] || 
             [ -z "${{ env.NODE_COUNT }}" ] || 
             [ -z "${{ env.ORGANIZATION }}" ] || 
             [ -z "${{ env.QUORUM_EXPLORER_IMAGE_TAG }}" ] || 
             [ -z "${{ env.SUBNET_NAME }}" ] || 
             [ -z "${{ env.VALIDATORS }}" ] || 
             [ -z "${{ env.ENV }}" ]; then
            echo "Error: One or more required environment variables are missing!"
            exit 1
          fi

            echo "Starting Ansible playbook with the following parameters:"
            echo "BESU_CONSENSUS_ALG=${{ env.BESU_CONSENSUS_ALG }}"
            echo "BOOTNODES=${{ env.BOOTNODES }}"
            echo "COMPONENT_ID=${{ env.COMPONENT_ID }}"
            echo "COMPONENT_NAME=${{ env.COMPONENT_NAME }}"
            echo "COUNTRY=${{ env.COUNTRY }}"
            echo "CUSTOMER_ID=${{ env.CUSTOMER_ID }}"
            echo "DNS_TYPE=${{ env.DNS_TYPE }}"
            echo "DNS_ZONE=${{ env.DNS_ZONE }}"
            echo "LOCATION=${{ env.LOCATION }}"
            echo "MIN_GAS_PRICE=${{ env.MIN_GAS_PRICE }}"
            echo "NET_NAME=${{ env.NET_NAME }}"
            echo "NETWORK_ID=${{ env.NETWORK_ID }}"
            echo "NODE_COUNT=${{ env.NODE_COUNT }}"
            echo "ORGANIZATION=${{ env.ORGANIZATION }}"
            echo "QUORUM_EXPLORER_IMAGE_TAG=${{ env.QUORUM_EXPLORER_IMAGE_TAG }}"
            echo "SUBNET_NAME=${{ env.SUBNET_NAME }}"
            echo "VALIDATORS=${{ env.VALIDATORS }}"
            echo "ENV=${{ env.ENV }}"

          cd ${{ vars.FOUNDATION_REPO_PATH }}
          if [ $? -ne 0 ]; then
            echo "Failed to change directory. Exiting pipeline."
            exit 1
          fi

          ansible-playbook -i inventories/hosts.yaml ${{ vars.NAMESPACE_PLAYBOOK }} --tags ${{ vars.TAGS }} -vvvv
          if [ $? -ne 0 ]; then
            echo "Ansible playbook execution failed. Exiting pipeline."
            exit 1
          else
            echo "Ansible playbook executed successfully. Namespace created."
          fi

  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: self-hosted
    needs: [create-namespace]
    environment: dev
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_GIT_ACCESS_TOKEN }}
          tenant-id: ${{ secrets.AZURE_GIT_ACCESS_TOKEN }}
          subscription-id: ${{ secrets.AZURE_GIT_ACCESS_TOKEN }}

