name: Hyperledger Besu Network
run-name: ${{ inputs.identifier }}

on:
  workflow_dispatch:
    inputs:         
      BESU_CONSENSUS_ALG: 
        description: 'Algorithm'
        type: string            
        default: "QBFT" 
      BOOTNODES: 
        description: 'Quantity'
        type: string    
        required: true
      COMPONENT_ID: 
        description: 'Component id'
        type: string  
        required: true
      COMPONENT_NAME: 
        description: 'Component name'
        type: string  
        required: true     
      COUNTRY: 
        description: 'country'
        type: string  
      CUSTOMER_ID: 
        description: 'customer id'
        type: string     
        required: true    
      DNS_TYPE: 
        description: 'dns type'
        type: string     
        default: "public"        
      identifier:
        description: 'Variable that represents the release identifier'
        required: true
        type: string  
      ENV:
        description: 'Variable that represents the environment'
        required: true
        type: string   

jobs:
  display-variables:
    name: "Teste"
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Use variables
      run: |
        echo "branch variable : $BRANCH"
        echo "ARTIFACT_REGISTRY variable : $ARTIFACT_REGISTRY"
        echo "CLIENT_ID variable : $CLIENT_ID"
        echo "secret : $AZURE_GIT_ACCESS_TOKEN"
      env:
        ARTIFACT_REGISTRY: ${{ vars.ARTIFACT_REGISTRY }}
        BRANCH: ${{ vars.BRANCH }}
        CLIENT_ID: ${{ vars.CLIENT_ID }}     
        AZURE_GIT_ACCESS_TOKEN: ${{ secrets.AZURE_GIT_ACCESS_TOKEN }}
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4

      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_GIT_ACCESS_TOKEN }}
          tenant-id: ${{ secrets.AZURE_GIT_ACCESS_TOKEN }}
          subscription-id: ${{ secrets.AZURE_GIT_ACCESS_TOKEN }}

